export const LOGIN = "LOGIN";
export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_LOGIN_STATE_PENDING = "SET_LOGIN_STATE_PENDING";
export const SET_LOGIN_STATE_FULFILLED = "SET_LOGIN_STATE_FULFILLED";
export const SET_LOGIN_STATE_REJECTED = "SET_LOGIN_STATE_REJECTED";
export const SET_JWT_TOKEN = "SET_JWT_TOKEN";
export const LOGOUT = "LOGOUT";
export const SET_RELOAD_PAGE = "SET_RELOAD_PAGE";
